[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/airbrake/gobrake"
  version = "3.2.0"

[[constraint]]
  name = "github.com/bugsnag/bugsnag-go"
  version = "1.1.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/rollbar/rollbar-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/getsentry/raven-go"
  version = "0.2.0"
