[[constraint]]
  name = "github.com/airbrake/gobrake"
  version = "3.0.1"

[[constraint]]
  name = "github.com/bugsnag/bugsnag-go"
  version = "1.1.1"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.7.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/vektra/mockery"

[prune]
  go-tests = true
  unused-packages = true
